export const belongingOptions = [
  { value: '1.1', label: 'בראשית' },
  { value: '1.2', label: 'נח' },
  { value: '1.3', label: 'לך לך' },
  { value: '1.4', label: 'וירא' },
  { value: '1.5', label: 'חיי שרה' },
  { value: '1.6', label: 'תולדות' },
  { value: '1.7', label: 'ויצא' },
  { value: '1.8', label: 'וישלח' },
  { value: '1.9', label: 'וישב' },
  { value: '1.10', label: 'מקץ' },
  { value: '1.11', label: 'ויגש' },
  { value: '1.12', label: 'ויחי' },

  { value: '2.1', label: 'שמות' },
  { value: '2.2', label: 'וארא' },
  { value: '2.3', label: 'בא' },
  { value: '2.4', label: 'בשלח' },
  { value: '2.5', label: 'יתרו' },
  { value: '2.6', label: 'משפטים' },
  { value: '2.7', label: 'תרומה' },
  { value: '2.8', label: 'תצוה' },
  { value: '2.9', label: 'כי תשא' },
  { value: '2.10', label: 'ויקהל' },
  { value: '2.11', label: 'פקודי' },

  { value: '3.1', label: 'ויקרא' },
  { value: '3.2', label: 'צו' },
  { value: '3.3', label: 'שמיני' },
  { value: '3.4', label: 'תזריע' },
  { value: '3.5', label: 'מצורע' },
  { value: '3.6', label: 'אחרי מות' },
  { value: '3.7', label: 'קדושים' },
  { value: '3.8', label: 'אמר' },
  { value: '3.9', label: 'בהר' },
  { value: '3.10', label: 'בחקתי' },

  { value: '4.1', label: 'במדבר' },
  { value: '4.2', label: 'נשא' },
  { value: '4.3', label: 'בהעלותך' },
  { value: '4.4', label: 'שלח' },
  { value: '4.5', label: 'קרח' },
  { value: '4.6', label: 'חקת' },
  { value: '4.7', label: 'בלק' },
  { value: '4.8', label: 'פנחס' },
  { value: '4.9', label: 'מטות' },
  { value: '4.10', label: 'מסעי' },

  { value: '5.1', label: 'דברים' },
  { value: '5.2', label: 'ואתחנן' },
  { value: '5.3', label: 'עקב' },
  { value: '5.4', label: 'ראה' },
  { value: '5.5', label: 'שופטים' },
  { value: '5.6', label: 'כי תצא' },
  { value: '5.7', label: 'כי תבוא' },
  { value: '5.8', label: 'נצבים' },
  { value: '5.9', label: 'וילך' },
  { value: '5.10', label: 'האזינו' },
  { value: '5.11', label: 'וזאת הברכה' },

  { value: '7.1', label: 'ראש השנה' },
  { value: '7.2', label: 'יום כיפור' },
  { value: '7.3', label: 'סוכות' },
  { value: '7.4', label: 'שמחת תורה' },
  { value: '7.5', label: 'חנוכה' },
  { value: '7.6', label: 'פורים' },
  { value: '7.7', label: 'פסח' },
  { value: '7.8', label: 'שבועות' },
  { value: '7.9', label: 'תשעה באב' }
];
